// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mirrors.dart';
import 'api/review.dart';
import 'api/simple.dart';
import 'api/terminal.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 752598176;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_claude_commander_client',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ApplyResult> crateApiReviewApplyComments({
    required String baseUrl,
    required String token,
    required String sessionId,
  });

  Stream<TerminalEvent> crateApiTerminalAttachTerminal({
    required String handle,
    required String baseUrl,
    required String token,
    required String sessionId,
  });

  Stream<TerminalEvent> crateApiTerminalBenchTerminalStream({
    required int chunks,
    required int chunkBytes,
  });

  Future<String> crateApiReviewCreateComment({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String file,
    required String side,
    required int lineStart,
    required int lineEnd,
    required String snippet,
    required String comment,
  });

  Future<String> crateApiSimpleCreateSession({
    required String baseUrl,
    required String token,
    required String projectPath,
    required String title,
    String? program,
    String? initialPrompt,
    String? effort,
    String? mode,
    String? baseBranch,
  });

  Future<void> crateApiReviewDeleteComment({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String commentId,
  });

  Future<void> crateApiSimpleDeleteSession({
    required String baseUrl,
    required String token,
    required String id,
  });

  Future<Uint8List> crateApiReviewFetchBlob({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String side,
    required String path,
  });

  Future<String?> crateApiSimpleGetPane({
    required String baseUrl,
    required String token,
    required String query,
    int? lines,
  });

  Future<SessionDetail?> crateApiSimpleGetSessionDetail({
    required String baseUrl,
    required String token,
    required String query,
    int? lines,
  });

  Future<bool> crateApiSimpleHealth({required String baseUrl});

  Future<bool> crateApiSimpleHealthTmux({
    required String baseUrl,
    required String token,
  });

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiSimpleKillSession({
    required String baseUrl,
    required String token,
    required String id,
  });

  Future<List<CommentDto>> crateApiReviewListComments({
    required String baseUrl,
    required String token,
    required String sessionId,
  });

  Future<List<SessionInfo>> crateApiSimpleListSessions({
    required String baseUrl,
    required String token,
    required bool includeStopped,
  });

  Future<ReviewSnapshotDto> crateApiReviewOpenReview({
    required String baseUrl,
    required String token,
    required String sessionId,
  });

  Future<ReviewSnapshotDto?> crateApiReviewRefreshReview({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String prevHash,
  });

  Future<void> crateApiSimpleRestartSession({
    required String baseUrl,
    required String token,
    required String id,
  });

  Future<void> crateApiTerminalTerminalDetach({required String handle});

  Future<void> crateApiTerminalTerminalResize({
    required String handle,
    required int cols,
    required int rows,
  });

  Future<void> crateApiTerminalTerminalSendInput({
    required String handle,
    required List<int> bytes,
  });

  Future<bool> crateApiReviewToggleFileReviewed({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String displayPath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ApplyResult> crateApiReviewApplyComments({
    required String baseUrl,
    required String token,
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_apply_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewApplyCommentsConstMeta,
        argValues: [baseUrl, token, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewApplyCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "apply_comments",
        argNames: ["baseUrl", "token", "sessionId"],
      );

  @override
  Stream<TerminalEvent> crateApiTerminalAttachTerminal({
    required String handle,
    required String baseUrl,
    required String token,
    required String sessionId,
  }) {
    final sink = RustStreamSink<TerminalEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(handle, serializer);
            sse_encode_String(baseUrl, serializer);
            sse_encode_String(token, serializer);
            sse_encode_String(sessionId, serializer);
            sse_encode_StreamSink_terminal_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiTerminalAttachTerminalConstMeta,
          argValues: [handle, baseUrl, token, sessionId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTerminalAttachTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "attach_terminal",
        argNames: ["handle", "baseUrl", "token", "sessionId", "sink"],
      );

  @override
  Stream<TerminalEvent> crateApiTerminalBenchTerminalStream({
    required int chunks,
    required int chunkBytes,
  }) {
    final sink = RustStreamSink<TerminalEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(chunks, serializer);
            sse_encode_u_32(chunkBytes, serializer);
            sse_encode_StreamSink_terminal_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiTerminalBenchTerminalStreamConstMeta,
          argValues: [chunks, chunkBytes, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTerminalBenchTerminalStreamConstMeta =>
      const TaskConstMeta(
        debugName: "bench_terminal_stream",
        argNames: ["chunks", "chunkBytes", "sink"],
      );

  @override
  Future<String> crateApiReviewCreateComment({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String file,
    required String side,
    required int lineStart,
    required int lineEnd,
    required String snippet,
    required String comment,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(file, serializer);
          sse_encode_String(side, serializer);
          sse_encode_u_32(lineStart, serializer);
          sse_encode_u_32(lineEnd, serializer);
          sse_encode_String(snippet, serializer);
          sse_encode_String(comment, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewCreateCommentConstMeta,
        argValues: [
          baseUrl,
          token,
          sessionId,
          file,
          side,
          lineStart,
          lineEnd,
          snippet,
          comment,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewCreateCommentConstMeta =>
      const TaskConstMeta(
        debugName: "create_comment",
        argNames: [
          "baseUrl",
          "token",
          "sessionId",
          "file",
          "side",
          "lineStart",
          "lineEnd",
          "snippet",
          "comment",
        ],
      );

  @override
  Future<String> crateApiSimpleCreateSession({
    required String baseUrl,
    required String token,
    required String projectPath,
    required String title,
    String? program,
    String? initialPrompt,
    String? effort,
    String? mode,
    String? baseBranch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(projectPath, serializer);
          sse_encode_String(title, serializer);
          sse_encode_opt_String(program, serializer);
          sse_encode_opt_String(initialPrompt, serializer);
          sse_encode_opt_String(effort, serializer);
          sse_encode_opt_String(mode, serializer);
          sse_encode_opt_String(baseBranch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleCreateSessionConstMeta,
        argValues: [
          baseUrl,
          token,
          projectPath,
          title,
          program,
          initialPrompt,
          effort,
          mode,
          baseBranch,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateSessionConstMeta =>
      const TaskConstMeta(
        debugName: "create_session",
        argNames: [
          "baseUrl",
          "token",
          "projectPath",
          "title",
          "program",
          "initialPrompt",
          "effort",
          "mode",
          "baseBranch",
        ],
      );

  @override
  Future<void> crateApiReviewDeleteComment({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String commentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(commentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewDeleteCommentConstMeta,
        argValues: [baseUrl, token, sessionId, commentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewDeleteCommentConstMeta =>
      const TaskConstMeta(
        debugName: "delete_comment",
        argNames: ["baseUrl", "token", "sessionId", "commentId"],
      );

  @override
  Future<void> crateApiSimpleDeleteSession({
    required String baseUrl,
    required String token,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleDeleteSessionConstMeta,
        argValues: [baseUrl, token, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeleteSessionConstMeta =>
      const TaskConstMeta(
        debugName: "delete_session",
        argNames: ["baseUrl", "token", "id"],
      );

  @override
  Future<Uint8List> crateApiReviewFetchBlob({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String side,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(side, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewFetchBlobConstMeta,
        argValues: [baseUrl, token, sessionId, side, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewFetchBlobConstMeta => const TaskConstMeta(
    debugName: "fetch_blob",
    argNames: ["baseUrl", "token", "sessionId", "side", "path"],
  );

  @override
  Future<String?> crateApiSimpleGetPane({
    required String baseUrl,
    required String token,
    required String query,
    int? lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(query, serializer);
          sse_encode_opt_box_autoadd_u_32(lines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetPaneConstMeta,
        argValues: [baseUrl, token, query, lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetPaneConstMeta => const TaskConstMeta(
    debugName: "get_pane",
    argNames: ["baseUrl", "token", "query", "lines"],
  );

  @override
  Future<SessionDetail?> crateApiSimpleGetSessionDetail({
    required String baseUrl,
    required String token,
    required String query,
    int? lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(query, serializer);
          sse_encode_opt_box_autoadd_u_32(lines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_session_detail,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetSessionDetailConstMeta,
        argValues: [baseUrl, token, query, lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetSessionDetailConstMeta =>
      const TaskConstMeta(
        debugName: "get_session_detail",
        argNames: ["baseUrl", "token", "query", "lines"],
      );

  @override
  Future<bool> crateApiSimpleHealth({required String baseUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleHealthConstMeta,
        argValues: [baseUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleHealthConstMeta =>
      const TaskConstMeta(debugName: "health", argNames: ["baseUrl"]);

  @override
  Future<bool> crateApiSimpleHealthTmux({
    required String baseUrl,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleHealthTmuxConstMeta,
        argValues: [baseUrl, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleHealthTmuxConstMeta => const TaskConstMeta(
    debugName: "health_tmux",
    argNames: ["baseUrl", "token"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSimpleKillSession({
    required String baseUrl,
    required String token,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleKillSessionConstMeta,
        argValues: [baseUrl, token, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleKillSessionConstMeta => const TaskConstMeta(
    debugName: "kill_session",
    argNames: ["baseUrl", "token", "id"],
  );

  @override
  Future<List<CommentDto>> crateApiReviewListComments({
    required String baseUrl,
    required String token,
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_comment_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewListCommentsConstMeta,
        argValues: [baseUrl, token, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewListCommentsConstMeta => const TaskConstMeta(
    debugName: "list_comments",
    argNames: ["baseUrl", "token", "sessionId"],
  );

  @override
  Future<List<SessionInfo>> crateApiSimpleListSessions({
    required String baseUrl,
    required String token,
    required bool includeStopped,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_bool(includeStopped, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleListSessionsConstMeta,
        argValues: [baseUrl, token, includeStopped],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListSessionsConstMeta => const TaskConstMeta(
    debugName: "list_sessions",
    argNames: ["baseUrl", "token", "includeStopped"],
  );

  @override
  Future<ReviewSnapshotDto> crateApiReviewOpenReview({
    required String baseUrl,
    required String token,
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_review_snapshot_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewOpenReviewConstMeta,
        argValues: [baseUrl, token, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewOpenReviewConstMeta => const TaskConstMeta(
    debugName: "open_review",
    argNames: ["baseUrl", "token", "sessionId"],
  );

  @override
  Future<ReviewSnapshotDto?> crateApiReviewRefreshReview({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String prevHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(prevHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_review_snapshot_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewRefreshReviewConstMeta,
        argValues: [baseUrl, token, sessionId, prevHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewRefreshReviewConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_review",
        argNames: ["baseUrl", "token", "sessionId", "prevHash"],
      );

  @override
  Future<void> crateApiSimpleRestartSession({
    required String baseUrl,
    required String token,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRestartSessionConstMeta,
        argValues: [baseUrl, token, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRestartSessionConstMeta =>
      const TaskConstMeta(
        debugName: "restart_session",
        argNames: ["baseUrl", "token", "id"],
      );

  @override
  Future<void> crateApiTerminalTerminalDetach({required String handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTerminalDetachConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTerminalDetachConstMeta =>
      const TaskConstMeta(debugName: "terminal_detach", argNames: ["handle"]);

  @override
  Future<void> crateApiTerminalTerminalResize({
    required String handle,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handle, serializer);
          sse_encode_u_16(cols, serializer);
          sse_encode_u_16(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTerminalResizeConstMeta,
        argValues: [handle, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTerminalResizeConstMeta =>
      const TaskConstMeta(
        debugName: "terminal_resize",
        argNames: ["handle", "cols", "rows"],
      );

  @override
  Future<void> crateApiTerminalTerminalSendInput({
    required String handle,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(handle, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTerminalSendInputConstMeta,
        argValues: [handle, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTerminalSendInputConstMeta =>
      const TaskConstMeta(
        debugName: "terminal_send_input",
        argNames: ["handle", "bytes"],
      );

  @override
  Future<bool> crateApiReviewToggleFileReviewed({
    required String baseUrl,
    required String token,
    required String sessionId,
    required String displayPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(displayPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReviewToggleFileReviewedConstMeta,
        argValues: [baseUrl, token, sessionId, displayPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReviewToggleFileReviewedConstMeta =>
      const TaskConstMeta(
        debugName: "toggle_file_reviewed",
        argNames: ["baseUrl", "token", "sessionId", "displayPath"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  RustStreamSink<TerminalEvent> dco_decode_StreamSink_terminal_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  UuidValue dco_decode_Uuid(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UuidValue.fromByteList(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  AgentState dco_decode_agent_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentState.values[raw as int];
  }

  @protected
  ApplyResult dco_decode_apply_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ApplyResult(
      kind: dco_decode_apply_result_kind(arr[0]),
      driftedIds: dco_decode_list_String(arr[1]),
      path: dco_decode_opt_String(arr[2]),
      count: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  ApplyResultKind dco_decode_apply_result_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApplyResultKind.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ReviewDecision dco_decode_box_autoadd_review_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_review_decision(raw);
  }

  @protected
  ReviewSnapshotDto dco_decode_box_autoadd_review_snapshot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_review_snapshot_dto(raw);
  }

  @protected
  SessionDetail dco_decode_box_autoadd_session_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_detail(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CommentDto dco_decode_comment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return CommentDto(
      id: dco_decode_String(arr[0]),
      file: dco_decode_String(arr[1]),
      side: dco_decode_review_comment_side(arr[2]),
      lineStart: dco_decode_u_32(arr[3]),
      lineEnd: dco_decode_u_32(arr[4]),
      snippet: dco_decode_String(arr[5]),
      comment: dco_decode_String(arr[6]),
      status: dco_decode_review_comment_status(arr[7]),
      createdAt: dco_decode_Chrono_Utc(arr[8]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CommentDto> dco_decode_list_comment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_comment_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReviewFileDto> dco_decode_list_review_file_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_review_file_dto).toList();
  }

  @protected
  List<ReviewHunkDto> dco_decode_list_review_hunk_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_review_hunk_dto).toList();
  }

  @protected
  List<ReviewLineDto> dco_decode_list_review_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_review_line_dto).toList();
  }

  @protected
  List<SessionInfo> dco_decode_list_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ReviewDecision? dco_decode_opt_box_autoadd_review_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_review_decision(raw);
  }

  @protected
  ReviewSnapshotDto? dco_decode_opt_box_autoadd_review_snapshot_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_review_snapshot_dto(raw);
  }

  @protected
  SessionDetail? dco_decode_opt_box_autoadd_session_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_session_detail(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PrState dco_decode_pr_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PrState.values[raw as int];
  }

  @protected
  ProjectId dco_decode_project_id(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ProjectId(field0: dco_decode_Uuid(arr[0]));
  }

  @protected
  ReviewCommentSide dco_decode_review_comment_side(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewCommentSide.values[raw as int];
  }

  @protected
  ReviewCommentStatus dco_decode_review_comment_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewCommentStatus.values[raw as int];
  }

  @protected
  ReviewDecision dco_decode_review_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewDecision.values[raw as int];
  }

  @protected
  ReviewFileDto dco_decode_review_file_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ReviewFileDto(
      displayPath: dco_decode_String(arr[0]),
      oldPath: dco_decode_String(arr[1]),
      newPath: dco_decode_String(arr[2]),
      status: dco_decode_review_file_status(arr[3]),
      added: dco_decode_u_32(arr[4]),
      removed: dco_decode_u_32(arr[5]),
      hunks: dco_decode_list_review_hunk_dto(arr[6]),
      isBinary: dco_decode_bool(arr[7]),
      binaryMime: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  ReviewFileStatus dco_decode_review_file_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewFileStatus.values[raw as int];
  }

  @protected
  ReviewHunkDto dco_decode_review_hunk_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ReviewHunkDto(
      oldStart: dco_decode_u_32(arr[0]),
      oldLines: dco_decode_u_32(arr[1]),
      newStart: dco_decode_u_32(arr[2]),
      newLines: dco_decode_u_32(arr[3]),
      header: dco_decode_String(arr[4]),
      lines: dco_decode_list_review_line_dto(arr[5]),
    );
  }

  @protected
  ReviewLineDto dco_decode_review_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ReviewLineDto(
      origin: dco_decode_review_line_origin(arr[0]),
      oldLineno: dco_decode_opt_box_autoadd_u_32(arr[1]),
      newLineno: dco_decode_opt_box_autoadd_u_32(arr[2]),
      content: dco_decode_String(arr[3]),
    );
  }

  @protected
  ReviewLineOrigin dco_decode_review_line_origin(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewLineOrigin.values[raw as int];
  }

  @protected
  ReviewSnapshotDto dco_decode_review_snapshot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ReviewSnapshotDto(
      base: dco_decode_String(arr[0]),
      contentHash: dco_decode_String(arr[1]),
      files: dco_decode_list_review_file_dto(arr[2]),
      comments: dco_decode_list_comment_dto(arr[3]),
      reviewed: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  SessionDetail dco_decode_session_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SessionDetail(
      info: dco_decode_session_info(arr[0]),
      agentState: dco_decode_agent_state(arr[1]),
      diffStat: dco_decode_opt_String(arr[2]),
      paneContent: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  SessionId dco_decode_session_id(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SessionId(field0: dco_decode_Uuid(arr[0]));
  }

  @protected
  SessionInfo dco_decode_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return SessionInfo(
      id: dco_decode_String(arr[0]),
      sessionId: dco_decode_session_id(arr[1]),
      title: dco_decode_String(arr[2]),
      branch: dco_decode_String(arr[3]),
      status: dco_decode_session_status(arr[4]),
      program: dco_decode_String(arr[5]),
      projectId: dco_decode_project_id(arr[6]),
      projectName: dco_decode_String(arr[7]),
      prNumber: dco_decode_opt_box_autoadd_u_32(arr[8]),
      prUrl: dco_decode_opt_String(arr[9]),
      prState: dco_decode_pr_state(arr[10]),
      prDraft: dco_decode_bool(arr[11]),
      prLabels: dco_decode_list_String(arr[12]),
      reviewDecision: dco_decode_opt_box_autoadd_review_decision(arr[13]),
      prReviewers: dco_decode_list_String(arr[14]),
      createdAt: dco_decode_Chrono_Utc(arr[15]),
    );
  }

  @protected
  SessionStatus dco_decode_session_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionStatus.values[raw as int];
  }

  @protected
  TerminalEvent dco_decode_terminal_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TerminalEvent(
      kind: dco_decode_terminal_event_kind(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
      text: dco_decode_String(arr[2]),
    );
  }

  @protected
  TerminalEventKind dco_decode_terminal_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TerminalEventKind.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  RustStreamSink<TerminalEvent> sse_decode_StreamSink_terminal_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return UuidValue.fromByteList(inner);
  }

  @protected
  AgentState sse_decode_agent_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AgentState.values[inner];
  }

  @protected
  ApplyResult sse_decode_apply_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_apply_result_kind(deserializer);
    var var_driftedIds = sse_decode_list_String(deserializer);
    var var_path = sse_decode_opt_String(deserializer);
    var var_count = sse_decode_u_32(deserializer);
    return ApplyResult(
      kind: var_kind,
      driftedIds: var_driftedIds,
      path: var_path,
      count: var_count,
    );
  }

  @protected
  ApplyResultKind sse_decode_apply_result_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApplyResultKind.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ReviewDecision sse_decode_box_autoadd_review_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_review_decision(deserializer));
  }

  @protected
  ReviewSnapshotDto sse_decode_box_autoadd_review_snapshot_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_review_snapshot_dto(deserializer));
  }

  @protected
  SessionDetail sse_decode_box_autoadd_session_detail(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_detail(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CommentDto sse_decode_comment_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_file = sse_decode_String(deserializer);
    var var_side = sse_decode_review_comment_side(deserializer);
    var var_lineStart = sse_decode_u_32(deserializer);
    var var_lineEnd = sse_decode_u_32(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    var var_comment = sse_decode_String(deserializer);
    var var_status = sse_decode_review_comment_status(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    return CommentDto(
      id: var_id,
      file: var_file,
      side: var_side,
      lineStart: var_lineStart,
      lineEnd: var_lineEnd,
      snippet: var_snippet,
      comment: var_comment,
      status: var_status,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CommentDto> sse_decode_list_comment_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CommentDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_comment_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReviewFileDto> sse_decode_list_review_file_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReviewFileDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_review_file_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ReviewHunkDto> sse_decode_list_review_hunk_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReviewHunkDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_review_hunk_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ReviewLineDto> sse_decode_list_review_line_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReviewLineDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_review_line_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SessionInfo> sse_decode_list_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReviewDecision? sse_decode_opt_box_autoadd_review_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_review_decision(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReviewSnapshotDto? sse_decode_opt_box_autoadd_review_snapshot_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_review_snapshot_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionDetail? sse_decode_opt_box_autoadd_session_detail(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_session_detail(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PrState sse_decode_pr_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PrState.values[inner];
  }

  @protected
  ProjectId sse_decode_project_id(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_Uuid(deserializer);
    return ProjectId(field0: var_field0);
  }

  @protected
  ReviewCommentSide sse_decode_review_comment_side(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReviewCommentSide.values[inner];
  }

  @protected
  ReviewCommentStatus sse_decode_review_comment_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReviewCommentStatus.values[inner];
  }

  @protected
  ReviewDecision sse_decode_review_decision(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReviewDecision.values[inner];
  }

  @protected
  ReviewFileDto sse_decode_review_file_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayPath = sse_decode_String(deserializer);
    var var_oldPath = sse_decode_String(deserializer);
    var var_newPath = sse_decode_String(deserializer);
    var var_status = sse_decode_review_file_status(deserializer);
    var var_added = sse_decode_u_32(deserializer);
    var var_removed = sse_decode_u_32(deserializer);
    var var_hunks = sse_decode_list_review_hunk_dto(deserializer);
    var var_isBinary = sse_decode_bool(deserializer);
    var var_binaryMime = sse_decode_opt_String(deserializer);
    return ReviewFileDto(
      displayPath: var_displayPath,
      oldPath: var_oldPath,
      newPath: var_newPath,
      status: var_status,
      added: var_added,
      removed: var_removed,
      hunks: var_hunks,
      isBinary: var_isBinary,
      binaryMime: var_binaryMime,
    );
  }

  @protected
  ReviewFileStatus sse_decode_review_file_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReviewFileStatus.values[inner];
  }

  @protected
  ReviewHunkDto sse_decode_review_hunk_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_oldStart = sse_decode_u_32(deserializer);
    var var_oldLines = sse_decode_u_32(deserializer);
    var var_newStart = sse_decode_u_32(deserializer);
    var var_newLines = sse_decode_u_32(deserializer);
    var var_header = sse_decode_String(deserializer);
    var var_lines = sse_decode_list_review_line_dto(deserializer);
    return ReviewHunkDto(
      oldStart: var_oldStart,
      oldLines: var_oldLines,
      newStart: var_newStart,
      newLines: var_newLines,
      header: var_header,
      lines: var_lines,
    );
  }

  @protected
  ReviewLineDto sse_decode_review_line_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_origin = sse_decode_review_line_origin(deserializer);
    var var_oldLineno = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_newLineno = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    return ReviewLineDto(
      origin: var_origin,
      oldLineno: var_oldLineno,
      newLineno: var_newLineno,
      content: var_content,
    );
  }

  @protected
  ReviewLineOrigin sse_decode_review_line_origin(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReviewLineOrigin.values[inner];
  }

  @protected
  ReviewSnapshotDto sse_decode_review_snapshot_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_base = sse_decode_String(deserializer);
    var var_contentHash = sse_decode_String(deserializer);
    var var_files = sse_decode_list_review_file_dto(deserializer);
    var var_comments = sse_decode_list_comment_dto(deserializer);
    var var_reviewed = sse_decode_list_String(deserializer);
    return ReviewSnapshotDto(
      base: var_base,
      contentHash: var_contentHash,
      files: var_files,
      comments: var_comments,
      reviewed: var_reviewed,
    );
  }

  @protected
  SessionDetail sse_decode_session_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_info = sse_decode_session_info(deserializer);
    var var_agentState = sse_decode_agent_state(deserializer);
    var var_diffStat = sse_decode_opt_String(deserializer);
    var var_paneContent = sse_decode_opt_String(deserializer);
    return SessionDetail(
      info: var_info,
      agentState: var_agentState,
      diffStat: var_diffStat,
      paneContent: var_paneContent,
    );
  }

  @protected
  SessionId sse_decode_session_id(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_Uuid(deserializer);
    return SessionId(field0: var_field0);
  }

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_session_id(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_branch = sse_decode_String(deserializer);
    var var_status = sse_decode_session_status(deserializer);
    var var_program = sse_decode_String(deserializer);
    var var_projectId = sse_decode_project_id(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_prNumber = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_prUrl = sse_decode_opt_String(deserializer);
    var var_prState = sse_decode_pr_state(deserializer);
    var var_prDraft = sse_decode_bool(deserializer);
    var var_prLabels = sse_decode_list_String(deserializer);
    var var_reviewDecision = sse_decode_opt_box_autoadd_review_decision(
      deserializer,
    );
    var var_prReviewers = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    return SessionInfo(
      id: var_id,
      sessionId: var_sessionId,
      title: var_title,
      branch: var_branch,
      status: var_status,
      program: var_program,
      projectId: var_projectId,
      projectName: var_projectName,
      prNumber: var_prNumber,
      prUrl: var_prUrl,
      prState: var_prState,
      prDraft: var_prDraft,
      prLabels: var_prLabels,
      reviewDecision: var_reviewDecision,
      prReviewers: var_prReviewers,
      createdAt: var_createdAt,
    );
  }

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SessionStatus.values[inner];
  }

  @protected
  TerminalEvent sse_decode_terminal_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_terminal_event_kind(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_text = sse_decode_String(deserializer);
    return TerminalEvent(kind: var_kind, bytes: var_bytes, text: var_text);
  }

  @protected
  TerminalEventKind sse_decode_terminal_event_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TerminalEventKind.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_terminal_event_Sse(
    RustStreamSink<TerminalEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_terminal_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.toBytes(), serializer);
  }

  @protected
  void sse_encode_agent_state(AgentState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_apply_result(ApplyResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_apply_result_kind(self.kind, serializer);
    sse_encode_list_String(self.driftedIds, serializer);
    sse_encode_opt_String(self.path, serializer);
    sse_encode_u_32(self.count, serializer);
  }

  @protected
  void sse_encode_apply_result_kind(
    ApplyResultKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_review_decision(
    ReviewDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_review_decision(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_review_snapshot_dto(
    ReviewSnapshotDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_review_snapshot_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_session_detail(
    SessionDetail self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_detail(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_comment_dto(CommentDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.file, serializer);
    sse_encode_review_comment_side(self.side, serializer);
    sse_encode_u_32(self.lineStart, serializer);
    sse_encode_u_32(self.lineEnd, serializer);
    sse_encode_String(self.snippet, serializer);
    sse_encode_String(self.comment, serializer);
    sse_encode_review_comment_status(self.status, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_comment_dto(
    List<CommentDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_comment_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_review_file_dto(
    List<ReviewFileDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_review_file_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_review_hunk_dto(
    List<ReviewHunkDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_review_hunk_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_review_line_dto(
    List<ReviewLineDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_review_line_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_session_info(
    List<SessionInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_review_decision(
    ReviewDecision? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_review_decision(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_review_snapshot_dto(
    ReviewSnapshotDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_review_snapshot_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_session_detail(
    SessionDetail? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_session_detail(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_pr_state(PrState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_project_id(ProjectId self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.field0, serializer);
  }

  @protected
  void sse_encode_review_comment_side(
    ReviewCommentSide self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_review_comment_status(
    ReviewCommentStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_review_decision(
    ReviewDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_review_file_dto(
    ReviewFileDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.displayPath, serializer);
    sse_encode_String(self.oldPath, serializer);
    sse_encode_String(self.newPath, serializer);
    sse_encode_review_file_status(self.status, serializer);
    sse_encode_u_32(self.added, serializer);
    sse_encode_u_32(self.removed, serializer);
    sse_encode_list_review_hunk_dto(self.hunks, serializer);
    sse_encode_bool(self.isBinary, serializer);
    sse_encode_opt_String(self.binaryMime, serializer);
  }

  @protected
  void sse_encode_review_file_status(
    ReviewFileStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_review_hunk_dto(
    ReviewHunkDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.oldStart, serializer);
    sse_encode_u_32(self.oldLines, serializer);
    sse_encode_u_32(self.newStart, serializer);
    sse_encode_u_32(self.newLines, serializer);
    sse_encode_String(self.header, serializer);
    sse_encode_list_review_line_dto(self.lines, serializer);
  }

  @protected
  void sse_encode_review_line_dto(
    ReviewLineDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_review_line_origin(self.origin, serializer);
    sse_encode_opt_box_autoadd_u_32(self.oldLineno, serializer);
    sse_encode_opt_box_autoadd_u_32(self.newLineno, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_review_line_origin(
    ReviewLineOrigin self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_review_snapshot_dto(
    ReviewSnapshotDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.base, serializer);
    sse_encode_String(self.contentHash, serializer);
    sse_encode_list_review_file_dto(self.files, serializer);
    sse_encode_list_comment_dto(self.comments, serializer);
    sse_encode_list_String(self.reviewed, serializer);
  }

  @protected
  void sse_encode_session_detail(SessionDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_info(self.info, serializer);
    sse_encode_agent_state(self.agentState, serializer);
    sse_encode_opt_String(self.diffStat, serializer);
    sse_encode_opt_String(self.paneContent, serializer);
  }

  @protected
  void sse_encode_session_id(SessionId self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.field0, serializer);
  }

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_session_id(self.sessionId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.branch, serializer);
    sse_encode_session_status(self.status, serializer);
    sse_encode_String(self.program, serializer);
    sse_encode_project_id(self.projectId, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_opt_box_autoadd_u_32(self.prNumber, serializer);
    sse_encode_opt_String(self.prUrl, serializer);
    sse_encode_pr_state(self.prState, serializer);
    sse_encode_bool(self.prDraft, serializer);
    sse_encode_list_String(self.prLabels, serializer);
    sse_encode_opt_box_autoadd_review_decision(self.reviewDecision, serializer);
    sse_encode_list_String(self.prReviewers, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
  }

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_terminal_event(TerminalEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_terminal_event_kind(self.kind, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_terminal_event_kind(
    TerminalEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
