// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/mirrors.dart';
import 'api/review.dart';
import 'api/simple.dart';
import 'api/terminal.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  RustStreamSink<TerminalEvent> dco_decode_StreamSink_terminal_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  AgentState dco_decode_agent_state(dynamic raw);

  @protected
  ApplyResult dco_decode_apply_result(dynamic raw);

  @protected
  ApplyResultKind dco_decode_apply_result_kind(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  ReviewDecision dco_decode_box_autoadd_review_decision(dynamic raw);

  @protected
  ReviewSnapshotDto dco_decode_box_autoadd_review_snapshot_dto(dynamic raw);

  @protected
  SessionDetail dco_decode_box_autoadd_session_detail(dynamic raw);

  @protected
  SessionId dco_decode_box_autoadd_session_id(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CommentDto dco_decode_comment_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CommentDto> dco_decode_list_comment_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReviewFileDto> dco_decode_list_review_file_dto(dynamic raw);

  @protected
  List<ReviewHunkDto> dco_decode_list_review_hunk_dto(dynamic raw);

  @protected
  List<ReviewLineDto> dco_decode_list_review_line_dto(dynamic raw);

  @protected
  List<SessionInfo> dco_decode_list_session_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  ReviewDecision? dco_decode_opt_box_autoadd_review_decision(dynamic raw);

  @protected
  ReviewSnapshotDto? dco_decode_opt_box_autoadd_review_snapshot_dto(
    dynamic raw,
  );

  @protected
  SessionDetail? dco_decode_opt_box_autoadd_session_detail(dynamic raw);

  @protected
  SessionId? dco_decode_opt_box_autoadd_session_id(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PrState dco_decode_pr_state(dynamic raw);

  @protected
  ProjectId dco_decode_project_id(dynamic raw);

  @protected
  ReviewCommentSide dco_decode_review_comment_side(dynamic raw);

  @protected
  ReviewCommentStatus dco_decode_review_comment_status(dynamic raw);

  @protected
  ReviewDecision dco_decode_review_decision(dynamic raw);

  @protected
  ReviewFileDto dco_decode_review_file_dto(dynamic raw);

  @protected
  ReviewFileStatus dco_decode_review_file_status(dynamic raw);

  @protected
  ReviewHunkDto dco_decode_review_hunk_dto(dynamic raw);

  @protected
  ReviewLineDto dco_decode_review_line_dto(dynamic raw);

  @protected
  ReviewLineOrigin dco_decode_review_line_origin(dynamic raw);

  @protected
  ReviewSnapshotDto dco_decode_review_snapshot_dto(dynamic raw);

  @protected
  SessionDetail dco_decode_session_detail(dynamic raw);

  @protected
  SessionId dco_decode_session_id(dynamic raw);

  @protected
  SessionInfo dco_decode_session_info(dynamic raw);

  @protected
  SessionStatus dco_decode_session_status(dynamic raw);

  @protected
  TerminalEvent dco_decode_terminal_event(dynamic raw);

  @protected
  TerminalEventKind dco_decode_terminal_event_kind(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  RustStreamSink<TerminalEvent> sse_decode_StreamSink_terminal_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  AgentState sse_decode_agent_state(SseDeserializer deserializer);

  @protected
  ApplyResult sse_decode_apply_result(SseDeserializer deserializer);

  @protected
  ApplyResultKind sse_decode_apply_result_kind(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  ReviewDecision sse_decode_box_autoadd_review_decision(
    SseDeserializer deserializer,
  );

  @protected
  ReviewSnapshotDto sse_decode_box_autoadd_review_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionDetail sse_decode_box_autoadd_session_detail(
    SseDeserializer deserializer,
  );

  @protected
  SessionId sse_decode_box_autoadd_session_id(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CommentDto sse_decode_comment_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CommentDto> sse_decode_list_comment_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReviewFileDto> sse_decode_list_review_file_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ReviewHunkDto> sse_decode_list_review_hunk_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ReviewLineDto> sse_decode_list_review_line_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionInfo> sse_decode_list_session_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  ReviewDecision? sse_decode_opt_box_autoadd_review_decision(
    SseDeserializer deserializer,
  );

  @protected
  ReviewSnapshotDto? sse_decode_opt_box_autoadd_review_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionDetail? sse_decode_opt_box_autoadd_session_detail(
    SseDeserializer deserializer,
  );

  @protected
  SessionId? sse_decode_opt_box_autoadd_session_id(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PrState sse_decode_pr_state(SseDeserializer deserializer);

  @protected
  ProjectId sse_decode_project_id(SseDeserializer deserializer);

  @protected
  ReviewCommentSide sse_decode_review_comment_side(
    SseDeserializer deserializer,
  );

  @protected
  ReviewCommentStatus sse_decode_review_comment_status(
    SseDeserializer deserializer,
  );

  @protected
  ReviewDecision sse_decode_review_decision(SseDeserializer deserializer);

  @protected
  ReviewFileDto sse_decode_review_file_dto(SseDeserializer deserializer);

  @protected
  ReviewFileStatus sse_decode_review_file_status(SseDeserializer deserializer);

  @protected
  ReviewHunkDto sse_decode_review_hunk_dto(SseDeserializer deserializer);

  @protected
  ReviewLineDto sse_decode_review_line_dto(SseDeserializer deserializer);

  @protected
  ReviewLineOrigin sse_decode_review_line_origin(SseDeserializer deserializer);

  @protected
  ReviewSnapshotDto sse_decode_review_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionDetail sse_decode_session_detail(SseDeserializer deserializer);

  @protected
  SessionId sse_decode_session_id(SseDeserializer deserializer);

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer);

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer);

  @protected
  TerminalEvent sse_decode_terminal_event(SseDeserializer deserializer);

  @protected
  TerminalEventKind sse_decode_terminal_event_kind(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_terminal_event_Sse(
    RustStreamSink<TerminalEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_agent_state(AgentState self, SseSerializer serializer);

  @protected
  void sse_encode_apply_result(ApplyResult self, SseSerializer serializer);

  @protected
  void sse_encode_apply_result_kind(
    ApplyResultKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_review_decision(
    ReviewDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_review_snapshot_dto(
    ReviewSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_detail(
    SessionDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_id(
    SessionId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_comment_dto(CommentDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comment_dto(
    List<CommentDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_review_file_dto(
    List<ReviewFileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_review_hunk_dto(
    List<ReviewHunkDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_review_line_dto(
    List<ReviewLineDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_info(
    List<SessionInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_review_decision(
    ReviewDecision? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_review_snapshot_dto(
    ReviewSnapshotDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_detail(
    SessionDetail? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_id(
    SessionId? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_pr_state(PrState self, SseSerializer serializer);

  @protected
  void sse_encode_project_id(ProjectId self, SseSerializer serializer);

  @protected
  void sse_encode_review_comment_side(
    ReviewCommentSide self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_review_comment_status(
    ReviewCommentStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_review_decision(
    ReviewDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_review_file_dto(ReviewFileDto self, SseSerializer serializer);

  @protected
  void sse_encode_review_file_status(
    ReviewFileStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_review_hunk_dto(ReviewHunkDto self, SseSerializer serializer);

  @protected
  void sse_encode_review_line_dto(ReviewLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_review_line_origin(
    ReviewLineOrigin self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_review_snapshot_dto(
    ReviewSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_detail(SessionDetail self, SseSerializer serializer);

  @protected
  void sse_encode_session_id(SessionId self, SseSerializer serializer);

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_terminal_event(TerminalEvent self, SseSerializer serializer);

  @protected
  void sse_encode_terminal_event_kind(
    TerminalEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
