// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

enum AgentState { working, idle, waitingForInput, unknown }

enum PrState { open, closed, merged }

class ProjectId {
  final UuidValue field0;

  const ProjectId({required this.field0});

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectId &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

enum ReviewDecision { reviewRequired, approved, changesRequested }

class SessionDetail {
  final SessionInfo info;
  final AgentState agentState;
  final String? diffStat;
  final String? paneContent;

  const SessionDetail({
    required this.info,
    required this.agentState,
    this.diffStat,
    this.paneContent,
  });

  @override
  int get hashCode =>
      info.hashCode ^
      agentState.hashCode ^
      diffStat.hashCode ^
      paneContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionDetail &&
          runtimeType == other.runtimeType &&
          info == other.info &&
          agentState == other.agentState &&
          diffStat == other.diffStat &&
          paneContent == other.paneContent;
}

class SessionId {
  final UuidValue field0;

  const SessionId({required this.field0});

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionId &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class SessionInfo {
  final String id;
  final SessionId sessionId;
  final String title;
  final String branch;
  final SessionStatus status;
  final String program;
  final ProjectId projectId;
  final String projectName;
  final int? prNumber;
  final String? prUrl;
  final PrState prState;
  final bool prDraft;
  final List<String> prLabels;
  final ReviewDecision? reviewDecision;
  final List<String> prReviewers;
  final DateTime createdAt;

  const SessionInfo({
    required this.id,
    required this.sessionId,
    required this.title,
    required this.branch,
    required this.status,
    required this.program,
    required this.projectId,
    required this.projectName,
    this.prNumber,
    this.prUrl,
    required this.prState,
    required this.prDraft,
    required this.prLabels,
    this.reviewDecision,
    required this.prReviewers,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      title.hashCode ^
      branch.hashCode ^
      status.hashCode ^
      program.hashCode ^
      projectId.hashCode ^
      projectName.hashCode ^
      prNumber.hashCode ^
      prUrl.hashCode ^
      prState.hashCode ^
      prDraft.hashCode ^
      prLabels.hashCode ^
      reviewDecision.hashCode ^
      prReviewers.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          title == other.title &&
          branch == other.branch &&
          status == other.status &&
          program == other.program &&
          projectId == other.projectId &&
          projectName == other.projectName &&
          prNumber == other.prNumber &&
          prUrl == other.prUrl &&
          prState == other.prState &&
          prDraft == other.prDraft &&
          prLabels == other.prLabels &&
          reviewDecision == other.reviewDecision &&
          prReviewers == other.prReviewers &&
          createdAt == other.createdAt;
}

enum SessionStatus {
  creating,
  running,
  stopped,
  merging,
  cascadePaused,
  pushing,
}
