// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mirrors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `base`

/// Liveness probe: `GET {base_url}/health` (no auth). Returns true on a 2xx.
Future<bool> health({required String baseUrl}) =>
    RustLib.instance.api.crateApiSimpleHealth(baseUrl: baseUrl);

/// Authenticated tmux probe: `GET {base_url}/api/health/tmux`. 200 → true,
/// 503 → false. Doubles as an auth check — a 401 surfaces as an error to Dart.
Future<bool> healthTmux({required String baseUrl, required String token}) =>
    RustLib.instance.api.crateApiSimpleHealthTmux(
      baseUrl: baseUrl,
      token: token,
    );

/// `GET {base_url}/api/sessions?include_stopped=` → the session list, decoded
/// into the shared `SessionInfo` wire type (frb mirrors it to a Dart class).
Future<List<SessionInfo>> listSessions({
  required String baseUrl,
  required String token,
  required bool includeStopped,
}) => RustLib.instance.api.crateApiSimpleListSessions(
  baseUrl: baseUrl,
  token: token,
  includeStopped: includeStopped,
);
