// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attach_inner`, `detached`, `error`, `lock_registry`, `output`, `ready`, `registry`, `remove_if_current`, `run_attach`, `runtime`, `ws_url`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Outbound`

/// Open a live terminal attach. `handle` is a caller-chosen id used to route
/// later `terminal_send_input`/`terminal_resize`/`terminal_detach` calls back to
/// this socket. Events stream over `sink` until the attach ends.
Stream<TerminalEvent> attachTerminal({
  required String handle,
  required String baseUrl,
  required String token,
  required String sessionId,
}) => RustLib.instance.api.crateApiTerminalAttachTerminal(
  handle: handle,
  baseUrl: baseUrl,
  token: token,
  sessionId: sessionId,
);

/// Send keystrokes / raw input bytes to an attached terminal. No-op if the
/// handle isn't attached (e.g. already detached).
Future<void> terminalSendInput({
  required String handle,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTerminalTerminalSendInput(
  handle: handle,
  bytes: bytes,
);

/// Tell the remote PTY the viewport changed.
Future<void> terminalResize({
  required String handle,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalTerminalResize(
  handle: handle,
  cols: cols,
  rows: rows,
);

/// Detach (leaves the tmux session running server-side).
Future<void> terminalDetach({required String handle}) =>
    RustLib.instance.api.crateApiTerminalTerminalDetach(handle: handle);

/// An event streamed from an attached terminal to Dart.
///
/// Modelled as a tagged struct (not a data-carrying enum) so frb generates a
/// plain Dart class — keeping the spike free of the freezed/build_runner
/// codegen step. If the project later adopts freezed, this can become a proper
/// sealed class.
class TerminalEvent {
  final TerminalEventKind kind;

  /// Populated only for [`TerminalEventKind::Output`]; empty otherwise.
  final Uint8List bytes;

  /// Session name (`Ready`), detach reason (`Detached`), or error message
  /// (`Error`); empty for `Output`.
  final String text;

  const TerminalEvent({
    required this.kind,
    required this.bytes,
    required this.text,
  });

  @override
  int get hashCode => kind.hashCode ^ bytes.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          bytes == other.bytes &&
          text == other.text;
}

/// Which kind of [`TerminalEvent`] this is. A unit-only enum so frb renders a
/// plain Dart enum (no freezed).
enum TerminalEventKind {
  /// Handshake done; the server echoed the resolved tmux session name (`text`).
  ready,

  /// Raw PTY output bytes in `bytes` — feed straight to the terminal emulator,
  /// which handles partial UTF-8 / escape sequences.
  output,

  /// The attach ended cleanly; `text` is the reason (client detach, session
  /// ended, transport).
  detached,

  /// A handshake or steady-state error; `text` is safe to show the user.
  error,
}
